# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: ddzx@759843

# 文件上传大小限制
  servlet:
    multipart:
    max-file-size: 10MB
    max-request-size: 100MB
# mybatis 配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# #阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5t98kqoyxZraSbzXoUoJ
    accessKeySecret: aDijx9hX3nuzuaeYUgrPjtpAGeRcMn
    bucketName: itheima-tlias-web

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug